basePath: /
definitions:
  usecase.CreateAccountUseCaseInput:
    properties:
      balance:
        type: integer
      cpf:
        type: string
      name:
        type: string
      secret:
        type: string
    type: object
  usecase.CreateAccountUseCaseOutput:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  usecase.FindAccountUseCaseOutput:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  usecase.FindBalanceByAccountUseCaseOutput:
    properties:
      balance:
        type: integer
    type: object
  usecase.LoginUseCaseInput:
    properties:
      cpf:
        type: string
      secret:
        type: string
    type: object
  usecase.LoginUseCaseOutput:
    properties:
      token:
        type: string
    type: object
  usecase.MakeTransferUseCaseAccount:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  usecase.MakeTransferUseCaseAccountInput:
    properties:
      id:
        type: string
    type: object
  usecase.MakeTransferUseCaseInput:
    properties:
      amount:
        type: integer
      destination_account:
        $ref: '#/definitions/usecase.MakeTransferUseCaseAccountInput'
    type: object
  usecase.MakeTransferUseCaseOutput:
    properties:
      amount:
        type: integer
      created_at:
        type: string
      destination_account:
        $ref: '#/definitions/usecase.MakeTransferUseCaseAccount'
      id:
        type: string
      origin_account:
        $ref: '#/definitions/usecase.MakeTransferUseCaseAccount'
    type: object
info:
  contact: {}
  description: This API aims to provide resources for common operations that occur
    within a bank.
  title: Bank API
  version: "1.0"
paths:
  /accounts:
    get:
      description: Find accounts by param
      parameters:
      - description: number of items to be returned per page
        in: query
        name: limit
        type: integer
      - description: page offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecase.FindAccountUseCaseOutput'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Find
      tags:
      - accounts
    post:
      description: Create account
      parameters:
      - description: create account request vody
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/usecase.CreateAccountUseCaseInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usecase.CreateAccountUseCaseOutput'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Create
      tags:
      - accounts
  /accounts/{account_id}/balance:
    get:
      description: Find balance of a specific accounts
      parameters:
      - description: account_id
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecase.FindBalanceByAccountUseCaseOutput'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Find
      tags:
      - accounts
  /login:
    post:
      description: Login checks that the user can use the API and returns a token
      parameters:
      - description: login request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/usecase.LoginUseCaseInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecase.LoginUseCaseOutput'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - accounts
  /transfers:
    get:
      description: Find transfers from an account(user needs to be authenticated)
      parameters:
      - description: number of items to be returned per page
        in: query
        name: limit
        type: integer
      - description: page offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecase.MakeTransferUseCaseOutput'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Find transfers by account
      tags:
      - transfers
    post:
      description: Create transfer between two accounts
      parameters:
      - description: make transfer request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/usecase.MakeTransferUseCaseInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usecase.MakeTransferUseCaseOutput'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create transfer
      tags:
      - transfers
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
