name: CDGitops

on:
  push:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build Go
      run: |
        go build -o bank-api cmd/server/main.go 

    - name: Test Go
      run: |
        go test ./...
